# Generated by Django 2.2 on 2020-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyallcharges',
            name='duration_unit',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'paid')], max_length=50, null=True),
        ),
    ]
